server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: 5535
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

aws:
  region: us-east-1
  s3:
    endpoint: http://localhost:4566
    bucket: resources
    access:
      key: secretkey
      id: secretkeyid